#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 15 20:44:58 2019

@author: scarletpasser
"""

DecYear = YR + float(MO - 1)/12 + float(DY - 1)/365.25 + float HR/(365.25) + float MN/(365.25*24*60) + float SC/(365.25*24*3600)